CREATE TABLE DAILY_LOG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_KEY VARCHAR(64) NOT NULL,
    LOG_DATE DATE NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT VARCHAR(5000) NOT NULL,
    VISIBILITY VARCHAR(20) NOT NULL,
    REACTION_COUNT BIGINT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE INDEX IDX_DAILY_LOG_MEMBER_DATE ON DAILY_LOG(MEMBER_KEY, LOG_DATE DESC);
CREATE INDEX IDX_DAILY_LOG_VISIBILITY_CREATED ON DAILY_LOG(VISIBILITY, CREATED_AT DESC);
