CREATE TABLE MEMBER (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    USER_ID VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(30) NOT NULL,
    NICKNAME VARCHAR(30) NOT NULL,
    INTRODUCE VARCHAR(1000),
    REACTION_CNT INT DEFAULT 0,
    ENABLED CHAR(1) DEFAULT 'Y',
    CREATED_AT TIME DEFAULT CURRENT_TIME,
    UPDATED_AT TIME,
    PRIMARY KEY(ID)
);

INSERT INTO MEMBER(USER_ID, PASSWORD, USER_NAME, NICKNAME) VALUES('ID1', 'PW1', 'USERNAME1', 'NICKNAME1');
INSERT INTO MEMBER(USER_ID, PASSWORD, USER_NAME, NICKNAME) VALUES('ID2', 'PW2', 'USERNAME2', 'NICKNAME2');
INSERT INTO MEMBER(USER_ID, PASSWORD, USER_NAME, NICKNAME) VALUES('ID3', 'PW3', 'USERNAME3', 'NICKNAME3');
INSERT INTO MEMBER(USER_ID, PASSWORD, USER_NAME, NICKNAME) VALUES('ID4', 'PW4', 'USERNAME4', 'NICKNAME4');
